# Generated by Django 3.0.5 on 2021-03-23 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11)),
                ('business_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Razón social')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('legal_representative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_representative_dni', models.CharField(blank=True, max_length=45, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre cultivo')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre fundo')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Business', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre estado')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('is_state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre zona')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Abreviatura')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre variable')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('cultivation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Cultivation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State')),
            ],
            options={
                'verbose_name': 'Variadad',
                'verbose_name_plural': 'Variedades',
            },
        ),
        migrations.CreateModel(
            name='Phenology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Indice')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre fenologia')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('cultivation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Cultivation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State')),
            ],
            options={
                'verbose_name': 'Fenologia',
                'verbose_name_plural': 'Fenologias',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telephone', models.CharField(blank=True, max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('photo', models.ImageField(blank=True, default='person/employee0.jpg', upload_to='person/')),
                ('charge', models.CharField(choices=[('1', 'Administrador'), ('2', 'Trabajador'), ('3', 'Otro')], default='1', max_length=1, verbose_name='Cargo')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre modulo')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Domain', verbose_name='Fundo')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre lote')),
                ('latitude', models.DecimalField(decimal_places=30, default=0, max_digits=30, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=30, default=0, max_digits=30, verbose_name='Longitud')),
                ('code_alternate1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo alterno 1')),
                ('code_alternate2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo alterno 2')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Module', verbose_name='Modulo')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='domain',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.Zone', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='cultivation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agricultural.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cultivation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
