# Generated by Django 3.0.5 on 2021-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural', '0002_auto_20210315_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='business',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
        migrations.AddField(
            model_name='person',
            name='charge',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Empleado'), ('3', 'Otro')], default='1', max_length=50, verbose_name='Cargo'),
        ),
    ]
