# Generated by Django 3.0.5 on 2021-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural', '0002_zone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Longitud'),
        ),
    ]
