# Generated by Django 3.0.5 on 2021-03-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural', '0003_auto_20210315_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='maternal_last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='names',
        ),
        migrations.RemoveField(
            model_name='person',
            name='paternal_last_name',
        ),
    ]
