# Generated by Django 3.0.5 on 2021-03-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural', '0003_auto_20210323_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='Longitud'),
        ),
    ]
