# Generated by Django 3.0.5 on 2021-03-24 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agricultural', '0004_auto_20210323_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre variedad'),
        ),
    ]
