# Generated by Django 3.0.5 on 2021-03-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural', '0004_auto_20210315_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='charge',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Empleado'), ('3', 'Otro')], default='1', max_length=1, verbose_name='Cargo'),
        ),
    ]
